import Head from 'next/head';

const Home = ({ testMessage, todo, query }) => {
  console.log({ testMessage, todo, query });
  const { id, title } = todo;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <h1>testMessage</h1>
        <p>
          {id} - {title}
        </p>
      </div>
    </div>
  );
};

const pupupu = async () => {
  const todoDataResponse = await fetch('https://jsonplaceholder.typicode.com/todos/1');
  const todoData = await todoDataResponse.json();
  return todoData;
};

// This gets called on every request
export async function getServerSideProps(context) {
  const todo = await pupupu();

  console.log('olocooo', todo);
  console.log('context', context.query);

  // Pass data to the page via props
  return {
    props: {
      testMessage: 'Testando a coisa',
      todo,
      query: context.query,
    },
  };
}

export default Home;
